"""Makes the IntelliJ Platform available to Bazel as an ordinary java dependency.

The jars come from one of two places:

  * a locally installed IDE, when the BORMENTAL_IDE_HOME environment variable points at
    one (either at the IDE home or at a macOS .app bundle).  Nothing is downloaded, and
    the IDE you already develop with is the IDE you compile against;

  * the pinned IntelliJ IDEA Community distribution below, when the variable is not set.
    That is what CI and a fresh checkout use.

To move to another platform version, change the three constants below.  The checksum is
printed by:

    curl -sL <url> | shasum -a 256
"""

_SDK_VERSION = "2026.2.1"

_SDK_URL = ("https://cache-redirector.jetbrains.com/intellij-repository/releases" +
            "/com/jetbrains/intellij/idea/ideaIC/{v}/ideaIC-{v}.zip".format(v = _SDK_VERSION))

_SDK_SHA256 = "562b3a2c72ce398cec98f33bca92aa629f96568b0f4dd75bb927e7c0523bb6d9"

_IDE_HOME_ENV = "BORMENTAL_IDE_HOME"

_BUILD_HEADER = """# Generated by //bzl:intellij_sdk.bzl -- do not edit.
load("@rules_java//java:defs.bzl", "java_import")

package(default_visibility = ["//visibility:public"])

exports_files(["ide_home.txt"])
"""

def _ide_home(rctx, raw_path):
    """Returns the IDE home, accepting both an IDE home and a macOS .app bundle."""
    path = rctx.path(raw_path)
    if not path.exists:
        fail("%s points at %s, which does not exist." % (_IDE_HOME_ENV, raw_path))
    if path.get_child("lib").exists:
        return path
    if path.get_child("Contents", "lib").exists:
        return path.get_child("Contents")
    fail("%s points at %s, which does not look like an IDE: no lib directory there." %
         (_IDE_HOME_ENV, raw_path))

def _jars_in(rctx, directory, repo_dir, link):
    """Lists the jars of one directory, linking them into the repository when needed."""
    if not directory.exists:
        return []
    jars = []
    for entry in directory.readdir():
        if entry.basename.endswith(".jar"):
            relative = repo_dir + "/" + entry.basename
            if link:
                rctx.symlink(entry, relative)
            jars.append(relative)
    return sorted(jars)

def _java_import(name, jars, comment):
    return """
# {comment}
java_import(
    name = "{name}",
    jars = {jars},
    neverlink = True,
)
""".format(name = name, jars = repr(jars), comment = comment)

def _intellij_sdk_impl(rctx):
    ide_home = rctx.os.environ.get(_IDE_HOME_ENV, "").strip()
    if ide_home:
        home = _ide_home(rctx, ide_home)
        link = True
    else:
        rctx.download_and_extract(
            url = _SDK_URL,
            sha256 = _SDK_SHA256,
            type = "zip",
        )
        home = rctx.path(".")
        link = False

    # Since 2024.2 the platform is split into per-module jars, part of them under lib/modules.
    jars = (_jars_in(rctx, home.get_child("lib"), "lib", link) +
            _jars_in(rctx, home.get_child("lib", "modules"), "lib/modules", link))
    if not jars:
        fail("No platform jars found in %s/lib." % home)

    build = [_BUILD_HEADER, _java_import("sdk", jars, "The platform itself.")]

    for plugin in rctx.attr.bundled_plugins:
        plugin_jars = _jars_in(
            rctx,
            home.get_child("plugins", plugin, "lib"),
            "plugins/" + plugin + "/lib",
            link,
        )
        if not plugin_jars:
            fail("Bundled plugin '%s' has no jars in %s/plugins/%s/lib." % (plugin, home, plugin))
        build.append(_java_import(
            "plugin_" + plugin.replace("-", "_"),
            plugin_jars,
            "Bundled plugin '%s'." % plugin,
        ))

    rctx.file("BUILD.bazel", "".join(build))

    # Consumed by tools/run-ide.sh, and handy when something has to be looked up by hand.
    rctx.file("ide_home.txt", str(home) + "\n")

intellij_sdk = repository_rule(
    implementation = _intellij_sdk_impl,
    attrs = {
        "bundled_plugins": attr.string_list(
            doc = "Names of bundled plugin directories to expose as :plugin_<name> targets.",
        ),
    },
    environ = [_IDE_HOME_ENV],
    configure = True,
    doc = "Exposes the IntelliJ Platform as :sdk, a compile-only java_import.",
)

def _intellij_impl(_mctx):
    intellij_sdk(
        name = "intellij_sdk",
        # Bundled plugins the plugin code is allowed to compile against.  DataGrip's
        # database support goes here as "DatabaseTools" once we start using it.
        bundled_plugins = [],
    )

intellij = module_extension(
    implementation = _intellij_impl,
    doc = "Declares the @intellij_sdk repository.",
)
